# Generated by Django 3.2.5 on 2021-08-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_alter_author_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='notas',
        ),
    ]
