# Generated by Django 3.2.5 on 2021-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_remove_author_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notas',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
