# Generated by Django 3.2.5 on 2021-08-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_author_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notas',
            field=models.TextField(default='no hay notas'),
        ),
    ]
